typography_spectrum: 0.31672
color:
  brandColors:
    - '#000000'
    - '#717d8d'
    - '#aabdc3'
    - '#2b3c44'
    - '#cbdce6'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.30205
analytics:
  google: null
  facebook: null
  twitter: null
name: Writing The Science Fiction Film
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Writing the Science Fiction Film
description: From"What if..?" to "WTF..?!"
purpose: []
