name: Writing The Science Fiction Film
favicon: null
layout_spectrum: 0.8586890830192715
typography_spectrum: 0.9277564403600991
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.00848373188637197
  lightness: 0.005922297248616815
  saturation: 0.1860291517805308
  rhythmicContrast: 0.14324094890616834
purpose: []
