name: Writing The Science Fiction Film
favicon: null
layout_spectrum: 0
typography_spectrum: 0.55891
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bedfc0'
    - '#ff7d6b'
    - '#000000'
    - '#591c09'
    - '#a28064'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
