name: Writing The Science Fiction Film
favicon: null
layout_spectrum: 0
typography_spectrum: 0.55891
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#717d8d'
    - '#aabdc3'
    - '#2b3c44'
    - '#cbdce6'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
